name: Deploy static content to Pages

on:
  # Se ejecuta cada vez que haces push a la rama main (o master)
  push:
    branches: ['main']
  # Permite ejecutar este flujo de trabajo manualmente desde la pestaña Actions
  workflow_dispatch:

# Otorga los permisos necesarios a GitHub Actions
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo un despliegue concurrente
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Trabajo de compilación (Build)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  # Trabajo de despliegue (Deploy)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4